source:
  uri: $SOURCE_DATABASE_URL
  version: 14

destination:
  uri: $DESTINATION_DB_URL
  name: association
  version: 14

upload:
  name: association
  source: $UPLOAD_SOURCE
  bucket: $BUCKET_NAME
