source:
  uri: $SOURCE_DATABASE_URL
  version: 14

destination:
  uri: $DESTINATION_DB_URL
  name: users
  version: 14

transformers:
  - users.sql

upload:
  name: users
  source: $UPLOAD_SOURCE
  bucket: $BUCKET_NAME
